blueprint:
  name: 小度音箱控制小米飞利浦灯泡
  description: 色温控制，模式控制（照明模式、休闲/放松模式、阅读模式、夜灯模式）
  domain: automation
  source_url: https://github.com/shaonianzhentan/conversation
  input:
    light_entity:
      name: 小米灯泡
      description: 小米飞利浦灯泡
      default: []
      selector:
        entity:
          domain: light
trigger:
- platform: event
  event_type: xiaodu_event
  event_data:
    domain: light
    entity_id: !input light_entity
action:
- variables:
    command: '{{ trigger.event.data.type }}'
- choose:
  - conditions:
    - '{{ command == "SetColorTemperatureRequest" }}'
    sequence:
      - service: light.turn_on
        data:
          color_temp: >
            {{ (333 + 175) - (333 - ((6500 - trigger.event.data.colorTemperatureInKelvin) / (6500 - 2700) * (333 - 175))) | int }}
          entity_id: !input light_entity
  - conditions:
    - '{{ command == "SetModeRequest" }}'
    sequence:
      - service: xiaomi_miio.light_set_scene
        data:
          scene: >
            {% set modes = {
                  "LIGHTING": 1,
                  "RELAX": 2,
                  "READING": 3,
                  "NIGHT_LIGHT": 4
                } 
            %}
            {{modes[trigger.event.data.mode]}}
          entity_id: !input light_entity